# Generated by Django 2.2.16 on 2023-01-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230115_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
